### ISSUE TITLE
0.7.0 migration guide

### ISSUE THREAD

**Issue by jamwaffles** [embedded-graphics/embedded-graphics#282]
Yep... starting this already :sweat_smile: 

(not a complete list - check closed issues/PRs and the 0.7 project)

* [ ] #274 #147 Circles are now defined by top left corner and diameter. To get the old behaviour, use `Circle::with_center`
* [ ] #342 Breaking `DrawTarget` trait changes

**Comment by rfuest** [comment]
Shouldn't this be included in the alpha project? IMO we don't need a polished nice migration guide, but at least an rough WIP version would help people who want to try the alpha version.
