### ISSUE TITLE
Add release checklist

### ISSUE THREAD

**Issue by rfuest** [embedded-graphics/embedded-graphics#382]
GitHub still considers 0.2.0 to be the latest release of e-g. The new layout now shows this on the front page of the repository:
![grafik](https://user-images.githubusercontent.com/226123/86019274-aea82480-ba26-11ea-88ba-df88c9497f4e.png)
This could make a visitor think that no new versions were released since 2018.

**Comment by jamwaffles** [comment]
That is _really_ annoying. This new Github interface is... mixed good/bad/horseshit.

I can draft a new release of e-g for 0.6.2 at that given commit which might fix things.

**Comment by rfuest** [comment]
I think you could create a release for the tag at: https://github.com/jamwaffles/embedded-graphics/tags

**Comment by jamwaffles** [comment]
Good tip, thanks. I've created a new release with a low-effort message to ask the user to look at `CHANGELOG.md`.

Looks like this now:

![image](https://user-images.githubusercontent.com/800791/86031159-5cb6cd00-ba2d-11ea-905c-d028a64b5624.png)

**Comment by rfuest** [comment]
That's better.
But this is one more thing we need to remember when doing a release, maybe we should create a release checklist.

**Comment by jamwaffles** [comment]
We should indeed. How would you suggest doing that? An issue template? A markdown document in the project root? Something in the readme?

**Comment by rfuest** [comment]
I wouldn't clutter the readme with this, because it isn't relevant for the normal user. IMO the markdown document in the project root would be the easiest solution.

**Comment by jamwaffles** [comment]
Sounds good to me. I've repurposed this issue to create a checklist in the root.

Items I can think of off the top of my head:

Pre-release:

* `cargo-release` must be used to release a crate in this repo.
* Is the changelog up to date, particularly with breaking changes?
* Is the version in `Cargo.toml` for the crate to be released the same as crates.io? (cargo-release automatically bumps to the next version)
* Double check which level (major, minor, patch) of release this is

Post-release

* Is the tag created by `cargo-release` pushed to Github?
* Is a Github release made for the latest version?

**Comment by rfuest** [comment]
I haven't done any release on crates.io yet, so I cannot comment on the details, but I think it looks good.
Maybe the pre-release checks should also contain that you need to make sure the latest CI build was successful.

**Comment by jamwaffles** [comment]
Yeah that definitely makes sense

**Comment by rfuest** [comment]
Should we announce all new releases on the matrix channel? Then this should also be add to the post-release section.

**Comment by jamwaffles** [comment]
Ooh, yes! This is specific to me, but it may also be worth adding a "make @jamwaffles tweet about it, tagging @ rust-embedded" as well. I think I have a few embedded Rust followers who would appreciate knowing about it.

**Comment by jamwaffles** [comment]
The Github CLI has a [`release` command](https://cli.github.com/manual/gh_release_create) which we may want to use to craft a GH release from the changelog. Not sure how feasible this is but it may be worth investigating.

**Comment by rfuest** [comment]
The GitHub releases weren't updated for e-g `0.7.0-alpha.3` and core `0.2.0` yet.

**Comment by rfuest** [comment]
The `simulator`, `tinytga` and `tinybmp` don't have any releases yet. Should we add pre-releases for the alpha versions or wait until the stable version?

**Comment by jamwaffles** [comment]
> The GitHub releases weren't updated for e-g 0.7.0-alpha.3 and core 0.2.0 yet.

Just updated these with the associated changelog items. Thanks for pointing that out.

> The simulator, tinytga and tinybmp don't have any releases yet. Should we add pre-releases for the alpha versions or wait until the stable version?

We should probably get some alphas out in case anybody wants to do some testing. Happy to get those released if you think it's a good idea.
