### ISSUE TITLE
Add vsync-esque method to DrawTarget trait

### ISSUE THREAD

**Issue by BroderickCarlin** [embedded-graphics/embedded-graphics#426]
## Description of the feature request

`embedded-graphics` currently lacks a trait method to provide functionality akin to the common vsync signal seen in displays. The primary benefit of providing such a method would be for displays that may double-buffer their pixel data to avoid displaying a half-updated image buffer.

It is my belief that adding such a method to the `DrawTarget` trait could be done in a way that is entirely backwards compatible as long as a default implementation is added. Any such default implementation would, by default, be nothing more than a no-op. 

Naming aside, a default implementation could be as simplistic as:
```
fn vsync(&mut self) {
    ()
}
```
and a display that implements something such as double buffering would be able to override the default implementation to provide the necessary logic.

This method would by default not actually be utilized anywhere else within the `embedded-graphics` crate but instead be a trait method to be utilized by crates that themselves build on-top of `embedded-graphics`. The reason for this is that this crate doesn't, as far as I can determine, have the concept of "drawing complete". For example, it wouldn't make sense to utilize this from within any single `Drawable` element since `Drawable` is intended to live on a per-element basis and multiple elements may comprise a single "frame".

In regards to naming, some possible options may be:
- `vsync()`
- `flush()`
- `finish()`
- ???

Obviously the implementation of this is near trivial so I am more curious to hear others thoughts on if they view this as something useful and any other potential options/solutions. A quick search of past issues/PR's didn't reveal any previous conversations but I would be surprised if this hadn't be considered in the past.

**Comment by rfuest** [comment]
A `flush` method existed at some point, but we decided to remove it. Here is a link to the discussion about it: https://github.com/jamwaffles/embedded-graphics/pull/243#issuecomment-574316449
