### ISSUE TITLE
Feature request/idea: specifying space width for variable width fonts

### ISSUE THREAD

**Issue by bugadani** [embedded-graphics/embedded-graphics#443]
To be fair, I didn't study the problem in depth, but right now, rendering text with a variable width font isn't particularly legible:

https://github.com/bugadani/embedded-text/blob/master/assets/variable_width.png

The main thing here is that a space is as wide as the "character spacing" option tells it to be. Even for 6x6, this looks weird and I think for bigger fonts it could mean that spaces can hardly be seen between words.

~The usability of variable width fonts would play a role in creating different font weights in a single font.~ Or maybe not :)

**Comment by jamwaffles** [comment]
Does #470 close this?

**Comment by bugadani** [comment]
Yes, for now.
