### ISSUE TITLE
Polyline end segment out of bounds draw

### ISSUE THREAD

**Issue by jamwaffles** [embedded-graphics/embedded-graphics#471]
- Version of embedded-graphics in use (if applicable): [version here]
- Target: simulator

## Description of the problem/feature request/other

For _some_ positions and thicknesses of polyline points, the end segment has screwed up rendering:

![image](https://user-images.githubusercontent.com/800791/99119052-86454f00-25f0-11eb-8bcb-d668cc4f3276.png)

Only happens at `stroke: 5` as far as I can tell. Ignore the triangle and horizontal blue line - that's from other test stuff.

Do bear in mind this is on a WIP branch where I've been messing around with line joints, so may not be reproducible in master - I'll check again when I'm in a clean enough state to `git checkout master`.

## Test case (if applicable)

```rust
let line_style = PrimitiveStyle::with_stroke(Rgb888::GREEN, 5);

let h = 100;

let mouse_pos = Point::new(137, 15);

let points = [
    Point::new(10, h / 2),
    Point::new(50, h / 2),
    Point::new(60, h / 2 - 20),
    Point::new(70, h / 2),
    Point::new(80, h / 2),
    Point::new(90, h / 2 + 10),
    Point::new(100, 10),
    Point::new(110, h / 2 + 20),
    Point::new(120, h / 2),
    mouse_pos,
];

Polyline::new(&points)
    .into_styled(line_style)
    .draw(display)?;
```

**Comment by rfuest** [comment]
You might have already checked, but I've just tested it in master and the error also exists there. There seems to be a problem with odd stoke widths when three points are almost on a straight line.

![grafik](https://user-images.githubusercontent.com/226123/99153108-b18a7580-26a6-11eb-8c41-78f85e811019.png)

```rust
for width in 1..20 {
    let pos = Point::new(width as i32 * 30, 0);

    Polyline::new(&points)
        .into_styled(PrimitiveStyle::with_stroke(Rgb888::GREEN, width))
        .draw(&mut display.translated(pos))?;

    Text::new(&width.to_string(), pos + Point::new(10, 80))
        .into_styled(TextStyle::new(Font6x8, Rgb888::WHITE))
        .draw(&mut display)?;
}

// 3 points on a straight line -> works
let points2 = [Point::new(10, 70), Point::new(20, 50), Point::new(30, 30)];

for width in 1..20 {
    let pos = Point::new(width as i32 * 30, 100);

    Polyline::new(&points2)
        .into_styled(PrimitiveStyle::with_stroke(Rgb888::RED, width))
        .draw(&mut display.translated(pos))?;

    Text::new(&width.to_string(), pos + Point::new(10, 80))
        .into_styled(TextStyle::new(Font6x8, Rgb888::WHITE))
        .draw(&mut display)?;
}
```

**Comment by jamwaffles** [comment]
Completely forgot to check in master :grimacing: thanks for the extra test case!

**Comment by jamwaffles** [comment]
Looks like it's in the `LineJoin` code somewhere. The middle join in the line is producing a `first_edge_end.left` and (they're the same) `second_edge_start.left` point of `32,5` which kicks it past the end. Will do a bit more digging.

**Comment by jamwaffles** [comment]
Further narrowed down to https://github.com/embedded-graphics/embedded-graphics/blob/master/src/primitives/line_join.rs#L158

**Comment by jamwaffles** [comment]
This has mostly mysteriously fixed itself, although now exhibits slightly different behaviour. Notice the right-side cap on the 19px wide green line:

![image](https://user-images.githubusercontent.com/800791/99878599-9cf63200-2bfe-11eb-8147-dc4a085bed98.png)

The widths for the second segment are still a pixel different, but I'm not sure we can do much about that without resorting to floating point.

**Comment by jamwaffles** [comment]
Changing the non working points to `let points = [Point::new(10, 70), Point::new(20, 50), Point::new(31, 30)];` now gets this result:

![image](https://user-images.githubusercontent.com/800791/99878632-d333b180-2bfe-11eb-85d2-4eca391e34d4.png)

**Comment by rfuest** [comment]
> This has mostly mysteriously fixed itself,...

`git bisect` revealed that the mysterious fix was included in this commit: c04430b9ae62cb773432535cc0b3fcb382ceab50

**Comment by jamwaffles** [comment]
With the `LinearEquation`s, is there a way of testing at which end of the line segment the intersection occurs? The issues above are caused by the intersection point being found on the "wrong end" of the line segments. One solution I thought up but failed to implement so far is to add a check to see where the intersections fall on both lines `l1` and `l2`, where `l1` is the right edge of the first polyline segment, and `l2` is the right edge of the second segment.

We could see if the intersection is on `l1` or _after_ `l1.end`, **and** on `l2` or _before_ `l2.start`. This would guarantee the intersection is constrained to both lines and the space between them.

If the intersection is on the wrong end of the lines as defined above, we could probably assume the lines are almost parallel at this point, and just pick the average between `l1.end` and `l2.start`.

**Comment by rfuest** [comment]
I don't think there is an easy way to tell on which side the intersection occurred using our current method.

The link you've added in the `intersection` method shows a method to implement this: http://paulbourke.net/geometry/pointlineplane/#i2l. The condition described in the last note could be extended to also include intersections after `l1.end` and `l2.start` by checking `u1 >= 0 && u2 <= 1`. But it would require some scaling or floating point to get the required resollution.
