### ISSUE TITLE
Thick polylines are drawn without translation

### ISSUE THREAD

**Issue by rfuest** [embedded-graphics/embedded-graphics#473]
Polylines with a stroke width > 1px don't use the `Polyline::translate` field and are always drawn without an offset.

Should we fix this issue or remove the `translate` field entirely, because polylines can also be translated by using a `TranslatedDrawTarget`? This would be a cleaner implementation IMO, but we would loose the ability to get the bounding box of a translated styled polyline.

**Comment by jamwaffles** [comment]
I'll look into this more later, but my immediate reaction is to keep the translatability of polylines to keep the surprise factor low - this way they keep similar features to other primitives.

**Comment by rfuest** [comment]
OK, but we could still use a translated draw target internally to reduce code duplication and remove the performance overhead for non translated polylines. The `Drawable` impl for styled polylines could be extended to directly draw to given draw target for non translated polylines or a translated draw target if the polyline is translated.
