### ISSUE TITLE
Old doc links

### ISSUE THREAD

**Issue by jamwaffles** [embedded-graphics/embedded-graphics#479]
Some old doc links point to `jamwaffles/embedded-graphics/embedded-graphics`. The redirect to `jamwaffles/embedded-graphics/embedded-graphics` works fine, however the `/embedded-graphics` _folder_ no longer exists. 

[This support issue](https://github.community/t/i-want-to-re-name-a-directory-how-do-i-redirect-so-that-my-existing-links-arent-broken/10568) suggests that the redirect/alias should work, but in my testing on `raw.githubusercontent` URLs it doesn't. Maybe it doesn't work on the raw domain, I dunno.

One option to try is a symlink like `ln -s ./embedded-graphics .` which may get old links working again.

Similar to #462.

See also https://github.com/embedded-graphics/embedded-graphics/issues/455#issuecomment-724868880.

**Comment by rfuest** [comment]
Should we close this? I don't think there is a good way of fixing the broken images in the older versions of the e-g docs and newer versions use inlined images.

**Comment by jamwaffles** [comment]
Yeah I think we can close this. As time and versions continue to increase, it will become even less relevant as well.
