### ISSUE TITLE
Triangle overdraw

### ISSUE THREAD

**Issue by jamwaffles** [embedded-graphics/embedded-graphics#489]
Triangles still exhibit overdraw in some cases. Removing the `set_allow_overdraw` calls in all the `triangle/styled.rs` tests result in two failures:  `bounding_box` and `styled_stroke_equals_lines`.

**Comment by rfuest** [comment]
I've also just encountered some overdraw with polylines, which might be related to this issue:
```rust
Polyline::new(&[
        Point::new(10, 5),
        Point::new(5, 10),
        Point::new(10, 10),
    ])
    .into_styled(PrimitiveStyle::with_stroke(Rgb888::RED, 5))
    .draw(&mut display)
    .unwrap();
```
