### ISSUE TITLE
Migrate tests to new MockDisplay assertion functions

### ISSUE THREAD

**Issue by rfuest** [embedded-graphics/embedded-graphics#501]
All tests, that compare a `MockDisplay` with an expected pattern, should use `MockDisplay::assert_pattern` or `MockDisplay::assert_eq`.

Some suggestion that came up in PR #493 should also be implemented:
* A basic unit test for the output https://github.com/embedded-graphics/embedded-graphics/pull/493#pullrequestreview-535978137
* Macros to allow assertions with messages https://github.com/embedded-graphics/embedded-graphics/pull/493#pullrequestreview-535980029
* A legend for the diff colors in the output https://github.com/embedded-graphics/embedded-graphics/pull/493#discussion_r528191078

**Comment by rfuest** [comment]
Do you think it would be useful to remove the `PartialEq` derive from `MockDisplay`? This might help in the migration and we wouldn't accidentally use `assert_eq!`.

**Comment by jamwaffles** [comment]
Yes, that would help. We have the `MockDisplay::assert_eq` method which can be used instead so removing the derive sounds fine to me.
