### ISSUE TITLE
Finish crate split

### ISSUE THREAD

**Issue by rfuest** [embedded-graphics/embedded-graphics#505]
From https://github.com/embedded-graphics/embedded-graphics/pull/498#pullrequestreview-540484691:

- [ ] Move `PointsIter` from into `embedded_graphics_core::iterator`
- [ ] Move `RawDataIter` into `embedded_graphics::iterator`
- [x] Check which types in the `iterator` module need to be in `core`
- [x] Try to remove draw target adapters, like `Clipped` or `ColorCoverted`, from `core`
- [x] Move `TextStyle` ~and `TextStylePixels`~ to `core`
- [x] Fix `tinybmp` and `tinytga` after new core release

**Comment by rfuest** [comment]
How will we document which e-g-core version is compatible with which e-g versions? Should a README file of an external crate mention the e-g-core version it's compatible with instead of the e-g version? The core version number might not be familiar for application developers who only depend on e-g itself.

**Comment by rfuest** [comment]
I just noticed that we missed to move the external font renderer support to the core crate.

**Comment by jamwaffles** [comment]
Dangit. What needs moving over though? I can see the `Text` struct and `TextStyle`/`TextStylePixels` traits, but I'm not sure what else.

**Comment by rfuest** [comment]
`TextStyle` and `TextStylePoints` should be in core and `Text` should stay in e-g. Additional traits might be added in the future to add frame text support.

**Comment by jamwaffles** [comment]
Both `TextStyle` and `TextStylePixels` (which is what I assume you mean by `TextStylePoints`) require `Text` though, so we'd have to move `Text` into core as well.

**Comment by rfuest** [comment]
Good point. I'm not sure yet if it's better to move `Text` into core or replace `Text` by `&str` and `Point` in `TextStyle` and `TextStylePixels`.

**Comment by jamwaffles** [comment]
I'm not sure either. At any rate, moving the text stuff into core won't be a breaking change as far as I can see, so we can do it at our leisure.

Maybe @bugadani can add some comments on what's required from e-g-core in terms of text.

**Comment by bugadani** [comment]
I think TextStyle and co. is rather renderer-specific, so I wouldn't necessarily move them. To be fair, I haven't had the time to dive into 0.7 and how it affects e-t. In the current versions, although I use TextStyle and TextStyleBuilder, they aren't strictly necessary. I treat e-t as it's own text renderer, and for that the most important dependency is the Font trait, besides the mechanisms to create my own pixel renderers.

I think I should spend some time with the new code, though, before I say anything legally binding.

**Comment by rfuest** [comment]
> I think TextStyle and co. is rather renderer-specific, so I wouldn't necessarily move them.

`TextStyle` was changed to be a trait and isn't renderer specific. The old `TextStyle` is now called `MonoTextStyle`.

**Comment by bugadani** [comment]
Interesting. Since it works with `Text` so closely, I don't *think* extracting it would make a difference for e-t, though. Kinda hard to describe a textbox using only a position :)

**Comment by rfuest** [comment]
#509 removes the `TextStylePixels` trait and replaces the `Text` arguments in the `TextStyle` methods, so that `Text` can stay in `embedded-graphics`.

**Comment by bugadani** [comment]
After porting e-t over to use e-g 0.7, I need to depend on the main crate instead of core for a number of reasons:
 - e-t implements the `Transform` trait for `TextBox` and co., which (the trait) is not present in `core`.
 - Currently e-t supports `MonoFont` by default. I could make this optional, behind a feature flag for example.
 - Current tests and examples are built on top of `MonoFont` support. I'll need to extend this to other font renderers, though.

If e-g core would include the `Transform` trait, e-t could be split into a renderer-agnostic core (some more cores and we'll have a cob of corn in our hands!), as well as a complete package with support for the most widely available font renderers.

**Comment by rfuest** [comment]
I would prefer to not add additional traits to the core crate at and have e-t depend on the main e-g crate instead. Because we control e-t it shouldn't be too hard to keep it compatible with the latest e-g version.

The `Transform` trait might change in the future and shouldn't be included in `core` at the moment IMO. Perhaps we could include it in a future version of e-g-core, if we recognize that it's necessary, but we should try to keep the core crate as small as possible.

**Comment by bugadani** [comment]
All right, depending on e-g proper works as well.

**Comment by jamwaffles** [comment]
Bumping this to see if we can close it or there's any more to do.

**Comment by rfuest** [comment]
I'll take another look and close it if I don't find anything more that needs to be done.

**Comment by jamwaffles** [comment]
It looks like the two unchecked items in the OP are no longer valid. The discussion now seems to be around text items which could be added to core as their own piece of work in the future, likely as a non-breaking change. With this in mind, I'll close this issue and we can open news ones in the future for other work.
