### ISSUE TITLE
Organization membership visibility

### ISSUE THREAD

**Issue by rfuest** [embedded-graphics/embedded-graphics#515]
I did change the visibility for my e-g organization membership to public a while back. If you aren't a member of the org the page for the e-g org now only shows my avatar:
![grafik](https://user-images.githubusercontent.com/226123/101374575-9dedbb80-38ae-11eb-9967-625350a9e6b5.png)

This makes me look more important than I am :wink: Should I change my membership visibility back to private or do @jamwaffles and @bugadani also want to set their visibility to public?

**Comment by jamwaffles** [comment]
All I do round here is polish @rfuest's socks and make coffee but...

I've changed my visibility to public anyway!

I'd suggest @bugadani do the same :)

**Comment by bugadani** [comment]
Thanks for the vote of confidence, now I can wear the membership with pride 😅

**Comment by jamwaffles** [comment]
The 3 musketeers are now public! Closing...

**Comment by rfuest** [comment]
Thanks for making my avatar feel less lonely on the org page!
