### ISSUE TITLE
Embedded-graphics device driver for Ableton Push 2 MIDI Instrument

### ISSUE THREAD

**Issue by mbracher** [embedded-graphics/embedded-graphics#520]
- Version of embedded-graphics in use: 0.6.2
- Target: Ableton Push 2
- If using real hardware: push2_display

## Description of the problem/feature request/other

Just wanting to let you know I created a device driver for the Ableton Push 2. 

[push2_display](https://crates.io/crates/push2_display)

**Comment by jamwaffles** [comment]
Heh that is awesome! I've added the driver to the list in the README and docs.rs main page in #521. Those lists will publicly update when the next release is cut.
