### ISSUE TITLE
Different naming of draw target and iterator adapters

### ISSUE THREAD

**Issue by rfuest** [embedded-graphics/embedded-graphics#529]
Similar adapter structs for draw targets and pixel iterators currently use slightly different names: `draw_target::Translated` vs `iterator::pixel::Translate`. Do you think this could be confusing for a user of the API and should we change one of the names?

**Comment by jamwaffles** [comment]
Changing `iterator::pixel::Translate` to `iterator::pixel::Translated` (and the fn to `.translated()`) makes more sense to me.

**Comment by rfuest** [comment]
SGTM.
