### ISSUE TITLE
Add return type to Drawable::draw

### ISSUE THREAD

**Issue by rfuest** [embedded-graphics/embedded-graphics#548]
`Drawable::draw` currently returns `Result<(), D::Error>` and doesn't allow to return any value. This is OK for most draw calls, but a return value would have an advantage for some.

Here is an example how this feature could be used to chain text drawing with different styles:
```rust
let next_point = Text::new("Label ", Point::new(10, 20)).into_styled(label_style).draw(&mut display)?;
Text::new("Value", next_point).into_styled(value_style).draw(&mut display)?;
```
By using the `next_point` value the size of the first text doesn't need to be calculated twice. This will only work for left aligned text, but for everything else we have e-t.

**Comment by jamwaffles** [comment]
That could be useful indeed. Would the impl look something like this:

```rust
pub trait Drawable {
    /// The pixel color type.
    type Color: PixelColor;

    type Output;

    /// Draw the graphics object using the supplied DrawTarget.
    fn draw<D>(&self, display: &mut D) -> Result<Self::Output, D::Error>
    where
        D: DrawTarget<Color = Self::Color>;
}
```

(and once [associated type defaults](https://doc.rust-lang.org/unstable-book/language-features/associated-type-defaults.html) are stable would make upgrading a lot less noisy for most users)

Aside: presumably this will happen after 0.7?

**Comment by rfuest** [comment]
Yes, it would look like this.

> Aside: presumably this will happen after 0.7?

`Drawable` is in the core crate and I would prefer to add it before the 0.7 release to make it less likely that we need to break the core crate for 0.8.
