### ISSUE TITLE
embedded-plots crate

### ISSUE THREAD

**Issue by mchodzikiewicz** [embedded-graphics/embedded-graphics#558]
Hi!

I have recently published plotting lib based on your crate. I would be grateful if you could review it since this is my first crate ever.

If you'll find it any good, please also consider adding link to it into your docs.

[embedded-plots](https://crates.io/crates/embedded-plots)

**Comment by jamwaffles** [comment]
That's awesome! Thanks for sharing :). I've added it to the list in the README in #559

**Comment by mchodzikiewicz** [comment]
Great, thanks!
