### ISSUE TITLE
Remove text rendering from core

### ISSUE THREAD

**Issue by rfuest** [embedded-graphics/embedded-graphics#564]
The support for external text renderers is still pretty new and IMO more likely to break in the future than the other parts of the core crate.

Should we remove the text rendering API from core for the 0.7 release? I think that keeping display drivers compatible is more important, because this affects a lot more crates by multiple authors.

Adding the text renderer API back into core would be a non breaking change. So that we could move the API back into core when we release e-g 0.8 or even earlier if we notice that the API was already perfect (very unlikely).

**Comment by jamwaffles** [comment]
Sounds good to me, let's do it.
