### ISSUE TITLE
Verify underline and strikethrough for bundled fonts

### ISSUE THREAD

**Issue by jamwaffles** [embedded-graphics/embedded-graphics#594]
This is an unchecked item from #511. I'm not entirely sure what it entails. It may already have been verified, in which case this issue can be closed without further work.

**Comment by jamwaffles** [comment]
I wrote a simple debug tool in embedded-graphics/debug-tools#11 which outputs this:

![image](https://user-images.githubusercontent.com/800791/119404516-d277f700-bcd7-11eb-92c3-942e710a07ff.png)

They all look good to me, so we could close this issue unless there's something I should be looking for and aren't.

**Comment by rfuest** [comment]
Thanks for taking a look at this and writing a debug tool.  I think it looks good.

One thing that might be worth trying would be to increase the height of the decorations for bold fonts (and maybe also large fonts) to 2px.

**Comment by jamwaffles** [comment]
No problem! Should we repurpose this ticket to make/experiment with those changes? If so, feel free to edit the title to match.
