### ISSUE TITLE
Support drawing a rectangular region of pixels.

### ISSUE THREAD

**Issue by derekdreery** [embedded-graphics/embedded-graphics#623]
Currently the `DrawTarget` methods supply a stream of pixels, with location and color data. On the ST7789 this is inefficient: the best way to move data to the screen is specifying a rectangle to draw to, and then the color data in column-major format. A method to do this would look something like (skipping some unimportant details for brevity)

```rust
trait DrawTarget {
    type Color;
    // ... maybe other methods
    fn draw_area(&mut self, area: Rectangle, data: impl IntoIterator<Item=Color>);
}
```

I don't know if other display hardware uses the same scheme. If they don't, then maybe there isn't a good way to abstract over getting pixels across fast. I'd like to hear others' ideas.

**Comment by kpreid** [comment]
This function already exists as [`DrawTarget::fill_contiguous`](https://docs.rs/embedded-graphics/0.7.1/embedded_graphics/draw_target/trait.DrawTarget.html#method.fill_contiguous) and seems to be [implemented for the ST7789](https://github.com/almindor/st7789/blob/master/src/graphics.rs#L64).

**Comment by derekdreery** [comment]
You're right sorry I missed that.
