### ISSUE TITLE
impl of `intersection` on `Rectangle`

### ISSUE THREAD

**Issue by derekdreery** [embedded-graphics/embedded-graphics#626]
I think `Rectangle::intersection` should return an `Option`. `Rectangle::zero()` is not the same as no rectangle.

**Comment by jamwaffles** [comment]
I think it's reasonable to return (and check for) `Rectangle::zero()` on no intersection, but I could be missing a usage scenario. Is it enough for your code to use `rect1.intersection(&rect2).is_zero_sized()` as a sentinel for "no intersection"? It would be good to see what issues you're getting in your code.

`Rectangle::zero()` vs an `Option` was discussed briefly in https://github.com/embedded-graphics/embedded-graphics/pull/342#discussion_r433470440 with the reasoning for `Rectangle::zero()` being that it already represents no intersection, so an added `Option` is unnecessary.
