### ISSUE TITLE
Allow zero-sized rectangles

### ISSUE THREAD

**Issue by derekdreery** [embedded-graphics/embedded-graphics#627]
This library currently represents zero-sized rectangles with an Option. If this were changed, some implementation code would be simplified, and branches removed.

The [`kurbo`](https://docs.rs/kurbo/0.8.1/) library (designed for floating point arithmetic) allows this, and in addition represents rectangles as edge coordinates, which again simplifies operations. Instinctively, it feels wrong that they allow negative width and height, but its use feels very ergonomic and natural.

**Comment by jamwaffles** [comment]
> This library currently represents zero-sized rectangles with an Option.

Not sure what you mean by this, sorry. We have `Rectangle::zero()` and `is_zero_sized()` which aren't `Option`s. Do you mean `bottom_right()` returning an `Option`?
