### ISSUE TITLE
How to rotate the Text?

### ISSUE THREAD

**Issue by hanusek** [embedded-graphics/embedded-graphics#658]
- Version of embedded-graphics in use (if applicable): 0.7.1
- Target: real hardware
- If using real hardware: OLED 1.3'' I2C

## Description of the problem
I would like render two text objects. The first - horizontal, the second - vertical.
How to do it?

```rust
    let builder = Builder::new()
    .with_rotation(DisplayRotation::Rotate90)
    .with_size(DisplaySize::Display128x64)
    .connect_i2c(i2c);

    let mut display: GraphicsMode<_> = builder.into();

    display.init().unwrap();
    display.flush().unwrap();

    let text_style = MonoTextStyleBuilder::new()
    .font(&FONT_6X10)
    .text_color(BinaryColor::On)
    .build();
    
    let text_point = Point::new(0, 0);
    Text::with_baseline("DEVICE", text_point, text_style, Baseline::Top).draw(&mut display).unwrap();

   // Rotate
    let text_point_rotated = //;
    Text::with_baseline("IP: 111.222.333.444", text_point_rotated, text_style, Baseline::Top).draw(&mut display).unwrap();
```

**Comment by rfuest** [comment]
Which type of vertical text do you mean?
![grafik](https://user-images.githubusercontent.com/226123/159777428-ea938cab-c608-479d-a5d5-6f83a5b29c82.png) or ![grafik](https://user-images.githubusercontent.com/226123/159777502-449000e1-95c0-46a1-a92b-b7aed40ade71.png)

There is no builtin support for either variant at the moment. But you can archive both by using some additional code. To implement the 2nd version you can implement a `DrawTarget` adapter, which rotates all drawing operations:
```rust
impl<'a, T> RotatedDrawTarget<'a, T>
where
    T: DrawTarget,
{
    pub fn new(parent: &'a mut T) -> Self {
        Self { parent }
    }
}

impl<T> DrawTarget for RotatedDrawTarget<'_, T>
where
    T: DrawTarget,
{
    type Color = T::Color;
    type Error = T::Error;

    fn draw_iter<I>(&mut self, pixels: I) -> Result<(), Self::Error>
    where
        I: IntoIterator<Item = Pixel<Self::Color>>,
    {
        let parent_width = self.parent.bounding_box().size.width as i32;

        self.parent.draw_iter(
            pixels
                .into_iter()
                .map(|Pixel(p, c)| Pixel(Point::new(parent_width - p.y, p.x), c)),
        )
    }
}

impl<T> Dimensions for RotatedDrawTarget<'_, T>
where
    T: DrawTarget,
{
    fn bounding_box(&self) -> Rectangle {
        let parent_bb = self.parent.bounding_box();
        Rectangle::new(
            parent_bb.top_left,
            Size::new(parent_bb.size.height, parent_bb.size.width),
        )
    }
}
```
And use it like this:
```rust
  Text::new(
        "Rotated text",
        Point::new(15, 15),
        MonoTextStyle::new(&FONT_5X8, BinaryColor::On),
    )
    .draw(&mut RotatedDrawTarget::new(&mut display))?;
```

**Comment by hanusek** [comment]
> ```rust
> RotatedDrawTarget
> ```

Thanks for reply.
Look 
![display_schema](https://user-images.githubusercontent.com/3663212/159782013-e7057e15-d953-444f-b2df-2a72c811b286.svg)

**Comment by rfuest** [comment]
Here is an example how this could be implemented in e-g: https://gist.github.com/rfuest/461b47aa16de08aa21be5428a107b9f7

![grafik](https://user-images.githubusercontent.com/226123/159791046-4844a7b7-6ece-4e29-87e1-c8a5b9805609.png)

**Comment by hanusek** [comment]
@rfuest You are great! Thx!
