### ISSUE TITLE
Additional functionallity by embedded-canvas

### ISSUE THREAD

**Issue by elpiel** [embedded-graphics/embedded-graphics#676]
Although it still needs some work and testing, it would be nice to add the `embedded-canvas` crate to the list of "additional functions provided by external crates"

- Version of embedded-graphics in use (if applicable): 0.3.3 (core)

https://crates.io/crates/embedded-canvas

**Comment by rfuest** [comment]
Please open a PR to add an entry to the crate list in the `src/lib.rs` docs and, if possible, run `just generate-readmes` to update the README. Updating the README needs some additional tooling: https://github.com/embedded-graphics/embedded-graphics/blob/master/doc/development-setup.md
