### ISSUE TITLE
`fixed` MSRV problems

### ISSUE THREAD

**Issue by jamwaffles** [embedded-graphics/embedded-graphics#683]
The build in #682 failed because `fixed` requires Rust 1.61 from version [1.16.0](https://gitlab.com/tspiteri/fixed/-/blob/master/RELEASES.md#version-1160-2022-06-30). We could:

1. Bump our MSRV again to whatever the latest version of Rust is at the time the bump is done.
2. Change our `Cargo.toml` to require 1.15 or less.

I think I'd prefer 1. as development on e-g has slowed a lot recently due to my focusses being elsewhere.

**Comment by Finomnis** [comment]
I agree with #1. Ideally, none of this would be necessary, because a change in MSRV would be a breaking change in SemVer. But I guess that's out of our control for dependency crates.

**Comment by jamwaffles** [comment]
Number 1 would also open the door to #674 so two birds, one stone...

**Comment by rfuest** [comment]
SGTM
