### ISSUE TITLE
Font Renderer: vertical alignment for multi-line strings

### ISSUE THREAD

**Issue by Finomnis** [embedded-graphics/embedded-graphics#692]
I noticed that multi-line strings always get aligned at the first line. This is fine for `Baseline::Top` and `Baseline::Alphabetic`, but I would have expected it to be aligned for the entire string for `Baseline::Bottom` and `Baseline::Middle`.

Implementing this should be fairly simple; iterating through the input string once to count the number of newlines should be very minor compared to the amount of computation required to do the actual rendering.

Is this an active design decision or was this just never implemented?
@rfuest

**Comment by jamwaffles** [comment]
I believe the current `Baseline` behaviour is correct; it should only shift the origin relative to the first line, e.g. `Baseline::Bottom` uses the bottom of the first character's bounding box as the text origin:

<img width="624" alt="image" src="https://user-images.githubusercontent.com/800791/190901397-ef3c4ae7-d8f2-4876-b963-db75d84f81d1.png">

If you want more involved alignment, I'd recommend [embedded-text](https://crates.io/crates/embedded-text). It can do much more clever stuff than vanilla e-g can:

```rust
let character_style = MonoTextStyle::new(&FONT_6X10, BinaryColor::On);

let textbox_style = TextBoxStyleBuilder::new()
    .alignment(HorizontalAlignment::Left)
    .vertical_alignment(VerticalAlignment::Bottom)
    .build();

TextBox::with_textbox_style(
    "This is a\nmultiline\nHello World!",
    display.bounding_box(),
    character_style,
    textbox_style,
)
.draw(&mut display)?;
```

**Comment by rfuest** [comment]
> Is this an active design decision or was this just never implemented?
> @rfuest

As @jamwaffles already answered: This behavior is intentional.

**Comment by Finomnis** [comment]
Got it.
