### ISSUE TITLE
New driver: st7567s

### ISSUE THREAD

**Issue by kattouf** [embedded-graphics/embedded-graphics#720]
Hi, please list a new driver supporting embedded-graphics:
https://crates.io/crates/st7567s

**Comment by rfuest** [comment]
Please open a PR if you want to add this driver to the list of supported drivers. Note that the source for the list is located in the doc comment at the top of `src/lib.rs` and duplicated in the README.

**Comment by kattouf** [comment]
https://github.com/embedded-graphics/embedded-graphics/pull/752
