### ISSUE TITLE
New Driver: ST7567

### ISSUE THREAD

**Issue by tracyspacy** [embedded-graphics/embedded-graphics#760]
Hi, 
please add a new driver for ST7567 LCD to the list: [https://crates.io/crates/st7567_rs](https://crates.io/crates/st7567_rs )

**Comment by rfuest** [comment]
Please open a PR to add your driver to the list. You need to update the list in `src/lib.rs` and either run `just generate-readmes` (which requires `just` and `cargo-readme` to be installed) or manually update `README.md`.
